package dev.rohin.userservice.model;


import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.util.List;

@Entity
@Table(name="users")
@Getter
@Setter
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // IDENTITY will rely on the Id generated by the Database
    private Long id;

    private String fullName;

    private  String password;

    private boolean active;

    @ManyToMany(fetch = FetchType.EAGER) // EAGER will fetch all the values with the other attributes
//    To load it together with the rest of the fields (i.e. eagerly)
    @JoinTable(name = "user_role", joinColumns = @JoinColumn(name = "user_id", referencedColumnName = "id"),
                            inverseJoinColumns = @JoinColumn(name = "role_id", referencedColumnName = "id"))
    private List<Role> roles;

//    https://www.baeldung.com/spring-mvc-custom-validator
    private String email;
}
